version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysqlsunucu
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_LOG_ERROR: "/var/log/mysql/error.log"
      MYSQL_GENERAL_LOG: "1"
      MYSQL_GENERAL_LOG_FILE: "/var/log/mysql/general.log"
      MYSQL_SLOW_QUERY_LOG: "1"
      MYSQL_SLOW_QUERY_LOG_FILE: "/var/log/mysql/slow.log"
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - wpnet
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/mysqld

  wordpress:
    image: wordpress:6.4-apache
    container_name: wpsunucu
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - wpvolume:/var/www/html
      - ./logs:/var/log/apache2
    networks:
      - wpnet
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/apache2

volumes:
  mysqlvolume:
  wpvolume:

networks:
  wpnet:
    driver: bridge
