version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysqlsunucu
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command: >
      --log-error=/var/log/mysql/error.log
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./logs/database:/var/log/mysql
    networks:
      - wpnet
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/mysqld

  wordpress:
    image: wordpress:6.4-apache
    container_name: wpsunucu
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - wpvolume:/var/www/html
      - ./logs/wordpress:/var/log/apache2
    networks:
      - wpnet
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/apache2

volumes:
  mysqlvolume:
  wpvolume:

networks:
  wpnet:
    driver: bridge
